name: Delivery Workflow

on:
  workflow_dispatch:

jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push API image
        uses: docker/build-push-action@v4
        with:
          context: ./ClienteAPI
          push: true
          tags: ghcr.io/${{ github.repository }}/api:latest

      - name: Deploy API
        run: |
          docker-compose up -d api

      - name: Wait for API to be ready
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:5135/health | grep -q "Healthy"; then
              echo "API is healthy"
              exit 0
            fi
            echo "Waiting for API to be healthy... ($i/30)"
            sleep 2
          done
          echo "API did not become healthy in time"
          exit 1

      - name: Query Prometheus for metric
        run: |
          curl -s "http://localhost:9090/api/v1/query?query=up" | jq . 